version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "bun"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "bun"
