name: Build, Lint and Test

on: [pull_request]

jobs:

  build:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Build and Test Server
        run: |
          bun install
          bun run prettier
          bun run lint
          bun run build
          bun test

      # Frontend tasks
      - name: Build Test Frontend
        working-directory: frontend
        run: |
          bun install
          bun run lint
          bun run prettier
          bun run build
          bun test
