name: Build, Lint and Test

on: [pull_request]

jobs:

  build:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun check
      - run: bun prettier
      - run: bun lint
      - run: bun test
